### ISSUE TITLE
Setup question

### ISSUE THREAD

**Issue by ado44** [zstenger93/data_science_piscine#1]
Hi i'm a 42 student and even if i haven't finish my CC, i ve started looking to this data science piscine. I ve noticed that you are recommending to launch everythin and have the csv file inside a docker images ? Can you explain what do you mean, how to do it and why ? Thanks

**Comment by zstenger93** [comment]
Hi, what do you mean by launching everything? I simply copied the csv files provided for the projects on the created Postgres container for easier access since we have no Postgres on the school computers and using VM's is horrible.

**Comment by ado44** [comment]
Hi thanks for your respond, ok i get it. This part in your readme "I recommend move all of your database csv files to the docker image and not trying to access it from outside which will reduce your headaches" confused me, the not trying to acces it from outside made thought that you were doing something in particular.
